version: 2.1

jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - run: |
          echo $SA > /sa.json
          cd service/ingatrack-api/ && ./mvnw -X verify
      - store_test_results:
          path: service/ingatrack-api/target/surefire-reports

workflows:
  maven_test:
    jobs:
      - build
